export const LIST_ALL = 'LIST_ALL';
export const INCREASE_INDEX = 'INCREASE_INDEX_CAROUSEL';
export const REDUCTION_INDEX = 'REDUCTION_INDEX_CAROUSEL';
export const INCREASE_TRENDINGINDEX = 'INCREASE_INDEX_TRENDINGCAROUSEL';
export const REDUCTION_ITRENDINGINDEX = 'REDUCTION_INDEX_TRENDINGCAROUSEL';