export const LIST_ALL = 'LIST_ALL';
export const INCREASE_INDEX = 'INCREASE_INDEX_CAROUSEL';
export const REDUCTION_INDEX = 'REDUCTION_INDEX_CAROUSEL';
export const INCREASE_TRENDINGINDEX = 'INCREASE_INDEX_TRENDINGCAROUSEL';
export const REDUCTION_ITRENDINGINDEX = 'REDUCTION_INDEX_TRENDINGCAROUSEL';
export const LIST_PRODUCT_TRENDING = 'LIST_PRODUCT_TRENDING';
export const LIST_PHONE_TRENDING = 'LIST_PHONE_TRENDING';
export const LIST_LAPTOP_TRENDING = 'LIST_LAPTOP_TRENDING';
